### ISSUE TITLE
Estas dessarallorando mas para Huayra?

### ISSUE THREAD

**Issue by juanroman74454811** [HuayraLinux/pkg-nwjs#1]

**Comment by juanroman74454811** [comment]
Porque pense que huayra tenia que finalizar,
A y tambien,
Puedo compilar estas apps en Windows?

**Comment by ftoledo** [comment]
hola @juanroman74454811  si se seguie avanzando! 
Nosotros desarrollamos sobre Huayra, no se si alguna app pueda andar sobre windows. Quizas con algunos ajustes si ya que el nw.js es multiplatarforma.

Podes seguir la actividad aca en github.

Saludos!
